site_name: "ontology association"
theme: readthedocs
nav:
  - Home: home.md
  - Index: index.md
  - Credits: credits.md
repo_url: https://github.com/biodatamodels/ontology-associations
site_url: http://biodatamodels.github.io/ontology-associations
