id: simple_gaf_association
schema_generating: true
description: ''
display_name: simple gaf association
document_category: simple gaf association
weight: 20
fields:
- id: db
  description: db part of identifier
  display_name: db
- id: local_id
  description: local part of identifier
  display_name: local id
- id: db_object_symbol
  display_name: db object symbol
- id: ontology_class_ref
  description: this must be a GO ID
  display_name: gaf association_ontology class ref
- id: supporting_references
  display_name: supporting references
  cardinality: multi
- id: evidence_type
  display_name: evidence type
- id: with_or_from
  display_name: with or from
  cardinality: multi
- id: aspect
  display_name: gaf association_aspect
- id: db_object_name
  display_name: db object name
- id: db_object_synonyms
  display_name: db object synonyms
  cardinality: multi
- id: db_object_type
  display_name: gaf association_db object type
- id: db_object_taxon
  display_name: db object taxon
- id: annotation_date
  description: date when annotation was made
  display_name: annotation date
- id: assigned_by
  description: assigned by
  display_name: assigned by
- id: annotation_extensions
  description: disjunction
  display_name: annotation extensions
  cardinality: multi
- id: gene_product_form
  description: isoform
  display_name: gene product form
- id: qualifiers
  display_name: simple gaf association_qualifiers
  cardinality: multi
